apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lilypad
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/arsen3d/argocd-example-apps'
    targetRevision: HEAD
    path: lilypad
    directory:
      recurse: false
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: lilypad
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
