apiVersion: apps/v1
kind: Deployment
metadata:
  name: appn
  namespace: lilypad
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appn
  template:
    metadata:
      labels:
        app: appn
    spec:
      containers:
      - name: appn
        image: jc21/nginx-proxy-manager:latest
        volumeMounts:
        - name: npm-data
          mountPath: /data
        - name: npm-letsencrypt
          mountPath: /etc/letsencrypt
        ports:
        - containerPort: 81
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"
      - name: cloudflared
        image: cloudflare/cloudflared:latest
        args:
        - "tunnel"
        - "run"
        - "--token"
        - "$(CLOUDFLARED_TOKEN)"
        env:
        - name: CLOUDFLARED_TOKEN
          valueFrom:
            secretKeyRef:
              name: lpauth
              key: CLOUDFLARED_TOKEN
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
      volumes:
      - name: npm-data
        persistentVolumeClaim:
          claimName: npm-data-pvc1
      - name: npm-letsencrypt
        persistentVolumeClaim:
          claimName: npm-letsencrypt-pvc1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: npm-data-pvc1
  namespace: lilypad
spec:
  # accessModes:
  #   - ReadWriteOnce 
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: npm-letsencrypt-pvc1
  namespace: lilypad
spec:
  # accessModes:
  #   - ReadWriteOnce 
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: lilypad
spec:
  selector:
    app: appn
  ports:
  - name: admin
    port: 81
    targetPort: 81
  # - name: http
  #   port: 80
  #   targetPort: 80
  # - name: https
  #   port: 443
  #   targetPort: 443