apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: lilypad
  labels:
    app: cloudflared
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      dnsPolicy: "None"  # Override default DNS policy
      dnsConfig:
        nameservers:
          - "1.1.1.1"
          - "8.8.8.8"
      containers:
      - name: cloudflared
        image: cloudflare/cloudflared:latest
        args:
        - "tunnel"
        - "--no-autoupdate"
        - "run"
        - "--token"
        - "$(CLOUDFLARED_TOKEN)"
        env:
        - name: CLOUDFLARED_TOKEN
          valueFrom:
            secretKeyRef:
              name: lpauth
              key: CLOUDFLARED_TOKEN
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
---
apiVersion: v1
kind: Service
metadata:
  name: cloudflared-metrics
spec:
  selector:
    app: cloudflared
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 44801
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-cloudflared-egress
spec:
  podSelector:
    matchLabels:
      app: cloudflared
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0  # Allow internet access
      ports:
        - protocol: UDP
          port: 7844
        - protocol: TCP
          port: 443
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-dns
  namespace: lilypad
spec:
  podSelector:
    matchLabels:
      app: cloudflared
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 1.1.1.1/32
    - ipBlock:
        cidr: 8.8.8.8/32
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53