apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: external-secrets
  labels:
    app.kubernetes.io/name: helm-repo
spec:
  url: https://charts.external-secrets.io
  interval: 1m0s
