apiVersion: apps/v1
kind: Deployment
metadata:
  name: lilypad-ui
  namespace: lilypad
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lilypad-ui
  template:
    metadata:
      labels:
        app: lilypad-ui
    spec:
      initContainers:
      - name: git-clone
        image: alpine/git
        command:
        - /bin/sh
        - -c
        - |
          git clone https://github.com/Lilypad-Tech/js-cli-wrapper.git /workspace
        volumeMounts:
        - name: workspace
          mountPath: /workspace
      
      containers:
      - name: run
        image: node:16
        ports:
        - containerPort: 3000   # Add this to expose the Node.js port
        command: 
        - /bin/sh
        - -c
        - |
          cd /workspace
          npm install
          npm run dev
          # cp -r build/* /build/
        volumeMounts:
        - name: workspace
          mountPath: /workspace
        # - name: build
        #   mountPath: /build
      # - name: nginx
      #   image: nginx:alpine
      #   ports:
      #   - containerPort: 80
      #   volumeMounts:
      #   # - name: build
      #   #   mountPath: /usr/share/nginx/html
      #   - name: nginx-config
      #     mountPath: /etc/nginx/conf.d
          
      volumes:
      - name: workspace
        emptyDir: {}
      # - name: build
      #   emptyDir: {}
      # - name: nginx-config
      #   configMap:
      #     name: nginx-config