apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod
  namespace: default
spec:
  restartPolicy: Never
  containers:
    - name: cuda-container
      image: nvcr.io/nvidia/k8s/cuda-sample:vectoradd-cuda12.5.0
      resources:
        limits:
          nvidia.com/gpu: 1 # requesting 1 GPU
          cpu: "1000m" # requesting 1 CPU
          memory: "2Gi" # requesting 2Gi of memory
  tolerations:
  - key: nvidia.com/gpu
    operator: Exists
    effect: NoSchedule