apiVersion: v1
kind: Pod
metadata:
  name: bacalhautest
  # namespace: default
spec:
  restartPolicy: Never
  containers:
    - name: bacalhautest
      image: ghcr.io/bacalhau-project/bacalhau:latest
      resources:
        limits:
          # nvidia.com/gpu: 1 # requesting 1 GPU
          cpu: "1000m" # requesting 1 CPU
          memory: "2Gi" # requesting 2Gi of memory
      # command:
      #   - "nvidia-smi"
      #   - "--query-gpu=name,memory.total,memory.free,memory.used,utilization.gpu,utilization.memory"
      #   - "--format=csv,noheader,nounits"
      command: ["bacalhau"]
      args: ["serve", "--orchestrator", "--compute"]
      # args: ["agent", "config"]
tolerations:
- key: nvidia.com/gpu
  operator: Exists
  effect: NoSchedule