apiVersion: apps/v1
kind: Deployment
metadata:
  name: lilypad-ui
  namespace: lilypad
  labels:
    app: lilypad-ui
    app.kubernetes.io/instance: lilypad
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lilypad-ui
  template:
    metadata:
      labels:
        app: lilypad-ui
        app.kubernetes.io/instance: lilypad
    spec:
      initContainers:
      - name: git-clone
        image: alpine/git
        command:
        - /bin/sh
        - -c
        - |
          git clone https://github.com/Lilypad-Tech/js-cli-wrapper.git /workspace
        volumeMounts:
        - name: workspace
          mountPath: /workspace
      
      containers:
      - name: run
        image: node:16
        ports:
        - containerPort: 3000
        envFrom:
        - secretRef:
            name: lpauth    # Reference to the secret containing env vars
        command: 
        - /bin/sh
        - -c
        - |
          cd /workspace
          npm install
          npm run dev
        volumeMounts:
        - name: workspace
          mountPath: /workspace
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
      # - name: nginx
      #   image: nginx:alpine
      #   ports:
      #   - containerPort: 80
      #   volumeMounts:
      #   # - name: build
      #   #   mountPath: /usr/share/nginx/html
      #   - name: nginx-config
      #     mountPath: /etc/nginx/conf.d
          
      volumes:
      - name: workspace
        emptyDir: {}
      # - name: build
      #   emptyDir: {}
      # - name: nginx-config
      #   configMap:
      #     name: nginx-config

---
apiVersion: v1
kind: Service
metadata:
  name: lilypad-ui-service
  namespace: lilypad
  labels:
    app: lilypad-ui
    app.kubernetes.io/instance: lilypad
spec:
  selector:
    app: lilypad-ui
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP