apiVersion: apps/v1
kind: Deployment
metadata:
  name: bacalhau
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bacalhau
  template:
    metadata:
      labels:
        app: bacalhau
    spec:
      restartPolicy: Always
      containers:
        - name: bacalhau
          image: ghcr.io/lilypad-tech/bacalhau:latest
          resources:
            limits:
              cpu: "1000m"
              memory: "2Gi"
          securityContext:
            capabilities:
              add: ["SYS_ADMIN","NET_RAW"]
            runAsUser: 0
            runAsGroup: 0
            privileged: true
          command:
            - /bin/sh
            - -c
            - "./run && bacalhau serve --orchestrator --compute"
          volumeMounts:
            - name: bacalhau-data
              mountPath: /root/.bacalhau
          env:
            - name: BACALHAU_ENVIRONMENT
              value: "local"
      volumes:
        - name: bacalhau-data
          emptyDir: {}
      tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule

---
apiVersion: v1
kind: Service
metadata:
  name: bacalhau
  namespace: lilypad
  labels:
    app: bacalhau
    app.kubernetes.io/instance: lilypad
spec:
  selector:
    app: bacalhau
  ports:
    - protocol: TCP
      port: 1234
      targetPort: 1234
  type: ClusterIP
