apiVersion: apps/v1
kind: Deployment
metadata:
  name: lilypad-ui
  namespace: lilypad
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lilypad-ui
  template:
    metadata:
      labels:
        app: lilypad-ui
    spec:
      initContainers:
      - name: git-clone
        image: alpine/git
        command:
        - /bin/sh
        - -c
        - |
          git clone https://github.com/Lilypad-Tech/js-cli-wrapper.git /workspace
        volumeMounts:
        - name: workspace
          mountPath: /workspace
      
      containers:
      - name: run
        image: node:16
        ports:
        - containerPort: 3000
        command: 
        - /bin/sh
        - -c
        - |
          cd /workspace
          npm install
          npm run dev
        volumeMounts:
        - name: workspace
          mountPath: /workspace
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf          
      volumes:
      - name: workspace
        emptyDir: {}
      - name: nginx-config
        configMap:
          name: nginx-config