apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubo
  template:
    metadata:
      labels:
        app: kubo
    spec:
      restartPolicy: Always
      initContainers:
        - name: init-config
          image: ipfs/kubo:latest
          command: ['sh', '-c', '
            ipfs init &&
            ipfs config --json API.HTTPHeaders.Access-Control-Allow-Origin "[\"*\"]" &&
            ipfs config --json API.HTTPHeaders.Access-Control-Allow-Methods "[\"PUT\", \"POST\", \"GET\"]" &&
            ipfs config --json API.HTTPHeaders.Access-Control-Allow-Credentials "[\"true\"]" &&
            ipfs config --json API.HTTPHeaders.Access-Control-Allow-Headers "[\"Authorization\", \"Content-Type\", \"X-Requested-With\", \"X-Stream-Output\", \"Range\"]" &&
            ipfs config Addresses.API /ip4/0.0.0.0/tcp/5001 &&
            ipfs config Addresses.Gateway /ip4/0.0.0.0/tcp/8080 &&
            ipfs config --json Gateway.HTTPHeaders.Access-Control-Allow-Origin "[\"*\"]" &&
            ipfs config --json Gateway.HTTPHeaders.Access-Control-Allow-Methods "[\"GET\"]" &&
            chown -R 1000:1000 /data/ipfs']
          volumeMounts:
            - name: ipfs-config
              mountPath: /data/ipfs
          securityContext:
            runAsUser: 0
      containers:
        - name: kubo
          image: ipfs/kubo:latest
          # args:
          #   - "COMPUTTE_MODE=gpu"
          resources:
            limits:
              cpu: "1000m"
              memory: "2Gi"
          env:
            - name: IPFS_API_HTTPHeaders_Access_Control_Allow_Origin
              value: "*"
            - name: IPFS_API_HTTPHeaders_Access_Control_Allow_Methods
              value: "PUT,POST,GET"
            - name: IPFS_API_HTTPHeaders_Access_Control_Allow_Credentials
              value: "true"
          volumeMounts:
            - name: ipfs-config
              mountPath: /data/ipfs
          securityContext:
            runAsUser: 1000
      volumes:
        - name: ipfs-config
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: kubo-rpc
spec:
  selector:
    app: kubo
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: kubo-gateway
spec:
  selector:
    app: kubo
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer