apiVersion: apps/v1
kind: Deployment
metadata:
  name: lilypad-ui
  labels:
    app: lilypad-ui
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lilypad-ui
  template:
    metadata:
      labels:
        app: lilypad-ui
    spec:
      initContainers:
      - name: git-clone
        image: alpine/git
        args:
        - clone
        - --single-branch
        - https://github.com/your-org/lilypad-ui.git
        - /workspace
        volumeMounts:
        - name: workspace
          mountPath: /workspace

      - name: build-push
        image: docker:latest
        workingDir: /workspace
        command: ["/bin/sh", "-c"]
        args:
        - |
          docker build -t registry:5000/lilypad-ui:latest .
          docker push registry:5000/lilypad-ui:latest
        volumeMounts:
        - name: workspace
          mountPath: /workspace
        - name: docker-socket
          mountPath: /var/run/docker.sock

      containers:
      - name: lilypad-ui
        image: registry:5000/lilypad-ui:latest
        ports:
        - containerPort: 80

      volumes:
      - name: workspace
        emptyDir: {}
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock
 
# ConfigMap for nginx configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
        listen 80;
        server_name localhost;
        
        location / {
            root /usr/share/nginx/html;
            try_files $uri $uri/ /index.html;
            index index.html;
        }
    }
 
apiVersion: v1
kind: Service
metadata:
  name: react-app-service
spec:
  selector:
    app: lilypad-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

apiVersion: v1
kind: ConfigMap
metadata:
  name: app-source
data:
  Dockerfile: |
    FROM node:16 AS builder
    WORKDIR /app
    COPY . .
    RUN npm install && npm run build

    FROM nginx:alpine
    COPY --from=builder /app/build /usr/share/nginx/html
    EXPOSE 80
    CMD ["nginx", "-g", "daemon off;"]