apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-proxy-manager
  namespace: lilypad
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-proxy-manager
  template:
    metadata:
      labels:
        app: nginx-proxy-manager
    spec:
      containers:
      - name: nginx-proxy-manager
        image: jc21/nginx-proxy-manager:2.11.2
        # envFrom:
        # - secretRef:
        #     name: npm-secret
        volumeMounts:
        - name: npm-data
          mountPath: /data
        - name: npm-letsencrypt
          mountPath: /etc/letsencrypt
        ports:
        - containerPort: 81
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"
      - name: cloudflare
        image: cloudflare/cloudflared:latest
        # command: ["cloudflared","tunnel","--no-autoupdate", "run", "--token", "${CLOUDFLARED_TOKEN}"]
        command: ["tunnel", "--no-autoupdate", "run", "--token", "${CLOUDFLARED_TOKEN}"]
        envFrom:
        - secretRef:
            name: lpauth
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"
      volumes:
      - name: npm-data
        persistentVolumeClaim:
          claimName: npm-data-pvc
      - name: npm-letsencrypt
        persistentVolumeClaim:
          claimName: npm-letsencrypt-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: npm-data-pvc
  namespace: lilypad
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: npm-letsencrypt-pvc
  namespace: lilypad
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy-manager
spec:
  selector:
    app: nginx-proxy-manager
  ports:
  - port: 81
    targetPort: 81