apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-secret-store
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        tokenSecretRef:
          name: vault-auth
          key: token
          namespace: vault
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: manager
  namespace: lilypad
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 5s
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: manager
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: secret/manager
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: resource-provider
  namespace: lilypad
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 5s
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: resource-provider
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: secret/resource-provider        
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pipeline
  namespace: lilypad
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 5s
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: pipeline
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: secret/pipeline                
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: services
  namespace: lilypad
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 5s
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: services
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: secret/services             