apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-secret-store
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        tokenSecretRef:
          name: vault-auth
          key: token
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-all-secrets
spec:
  refreshInterval: 5s
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: manager
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: secret/manager