# Bootstrap secret for Vault authentication
# NOTE: Replace 'root' with your actual Vault token after Vault is initialized
# For dev mode Vault, the root token is 'root'
# For production, use a proper auth method (Kubernetes auth, AppRole, etc.)
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-auth
  namespace: vault
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
type: Opaque
stringData:
  token: "root"  # Replace with actual Vault token
