apiVersion: v1
kind: Service
metadata:
  name: lp-vault
  namespace: lilypad
  # labels:
  #   app.kubernetes.io/instance: vault
  #   app.kubernetes.io/name: vault
  #   apps.kubernetes.io/pod-index: "0"
  #   component: server
  #   controller-revision-hash: vault-b75cdb86b
  #   helm.sh/chart: vault-0.29.1
  #   statefulset.kubernetes.io/pod-name: vault-0
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8200
      targetPort: 8200
    - name: https-internal
      protocol: TCP
      port: 8201
      targetPort: 8201
  selector:
    app.kubernetes.io/name: vault
    app.kubernetes.io/instance: vault-0
    # app.kubernetes.io/namespace: vault
  type: LoadBalancer